# Generated by Django 3.0.6 on 2020-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=48)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
